esphome:
  name: esp-daikin-ctrl
  friendly_name: "ESP32 WiFi Daikin Controller"
  name_add_mac_suffix: True

  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf
  variant: ESP32C3

# Enable logging
logger:
  level: VERY_VERBOSE
  hardware_uart: USB_SERIAL_JTAG
  baud_rate: 2500000

#Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ap:
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  # fast_connect: true

captive_portal: 

external_components:
  - source: components

status_led:
    pin: GPIO4

climate:
  - platform: daikin_ducted
    id: daikin0
    name: "Ducted AC"
