# This is a basic workflow to help you get started with Actions

name: esphome-build

on:
  create: { }
  push: { }
  pull_request: { }

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Run esphome build
        run: |
          pip install esphome
          esphome compile esphome/esp-daikin-ctrl.yaml
