name: esphome-build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ESPHOME_VERSION: "2026.4.0"
  ESPHOME_CONFIG: esphome/esp-daikin-ctrl.yaml

jobs:
  build:
    name: Build firmware
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Build firmware
        id: esphome-build
        uses: esphome/build-action@v7
        with:
          yaml-file: ${{ env.ESPHOME_CONFIG }}
          version: ${{ env.ESPHOME_VERSION }}
          complete-manifest: true

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.esphome-build.outputs.original-name }}-firmware
          path: ${{ steps.esphome-build.outputs.name }}
